### ISSUE TITLE
24.2_Hygrothermograph

### ISSUE THREAD

**Issue by Portals72** [Freenove/Freenove_Ultimate_Starter_Kit_for_ESP32#7]
Warning: I2C(-1, ...) is deprecated, use SoftI2C(...) instead
Traceback (most recent call last):
  File "<stdin>", line 10, in <module>
  File "I2C_LCD.py", line 21, in __init__
OSError: [Errno 19] ENODEV

**Comment by Shaynee-MO** [comment]
Hi, please modify the code as below and try again.
![image](https://user-images.githubusercontent.com/118493923/216226834-2be54842-b7de-4b27-8a07-06ba2a643a72.png)

**Comment by Portals72** [comment]
That works after editing the I2C_LCD.py and Hygrothemograph.py

Still get this error in Terminal, but Temperature and Humidity display.

Warning: I2C(-1, ...) is deprecated, use SoftI2C(...) instead

![IMG_3110](https://user-images.githubusercontent.com/74387646/216394119-c9c778be-2bec-4fda-abe4-c028b0dc180f.JPG)
![IMG_3111](https://user-images.githubusercontent.com/74387646/216394144-84d1fca8-cdb9-48fe-8d32-bef5f60ebc36.JPG)

**Comment by Shaynee-MO** [comment]
That warning does not matter. You can just ignore it.
